SafetyCulture/SafetyCulture-Power-Query-Connector

iAuditor.pq

This change adds `web_report_link` to `inspections` table.

INTG-1597: add web report link

---

iAuditor.pq
iAuditor.query.pq

Added `template_permissions` table that allows customers to access permissions assigned to templates.

INTG-1608 add template permissions table

---

README.md

Adding a FAQ page - this is also mirrored to our support page [here](https://help.safetyculture.com/en_us/1064273113-Hyv7g_tVv).

[INTG-1620] Updating readme.md with FAQ

---

iAuditor.pq
iAuditor.query.pq

Introduces actions tables to Power BI connector.
Actions and Actions Assignees provide the ability to fetch high level action data.

[INTG-1584] Add actions tables

---

iAuditor.pq

These changes will enable users to use the OAuth 2.0 flow and connect to their account directly without needing to enter an API key.

INTG-1739: OAuth support

---

iAuditor.pq

Media_ids added to inspection items Table 
completed_at added to actions Table

INTG-1735-add-addtional-columns-to-Bi-integrations-and-iAuditor-Exporter

---

iAuditor.pq

Surface `template_name` in inspections, which is required for Qatar Tourism PowerBI reporting purposes.

[BSA-3761] Include template_name in inspections

---

iAuditor.pq

Adds flag to fetch full site hierarchy and meta data to structure the data.

[INTG-2270] Add site hierarchy metadata and flag

---

iAuditor.pq

Add support for the site members table.

[INTG-2229] Add Site Members table

---

iAuditor.pq

Depends on https://github.com/SafetyCulture/thepub/pull/1016

[CSE-5] Add completed_at on issues data

---

SafetyCulture.pq

this PR:
- support for action label in actions feed

INTG-2578 actions feed - add action labels

---

SafetyCulture.pq
SafetyCulture.query.pq

Add support for:
- Action timeline data feeds
- Issue timeline data feeds
---

INTG-2230 add data feeds - action timeline, issue timeline

---

SafetyCulture.pq

Update actionType to include action sequential number (`unique_id`) for data import.
---

INTG-2724 add unique ID to action feed

---

SafetyCulture.pq

This PR adds two new fields exposed by our data feeds
---

[CSE-78] Add primeelement ID and index

---

README.md
SafetyCulture.pq

The Feed Issues will return a new element: unique_id
---

INTG-2972 add  unique_id for issues feed

---

SafetyCulture.pq

Add AssetID to the feed schedules
- ...
---

INTG-3242 add asset id to the feed schedules

---

SafetyCulture.pq

Add SeatType to the feed users
- ...
---

INTG-3202 add seat type to the feed users

---

SafetyCulture.pq
SafetyCulture.query.pq

Added issue assignees feed
- ...
---

INTG-3306 - Added issue assignees feed

---

SafetyCulture.pq
SafetyCulture.query.pq

INTG-3307 - adding note field to schedule occurrences

---

.github/CODEOWNERS

DEVP-3440 team rename

---

SafetyCulture.pq

DEVP-3557 add occurred_at
